#!/usr/bin/env bash
set -euo pipefail

export PORT="${PORT:-3000}"
export IMGPROXY_NETWORK="${IMGPROXY_NETWORK:-unix}"

if [[ "$IMGPROXY_NETWORK" == unix* ]]; then
  export IMGPROXY_BIND="${IMGPROXY_BIND:-/tmp/imgproxy.sock}"
  export IMGPROXY_UNIX_SOCKET="${IMGPROXY_UNIX_SOCKET:-$IMGPROXY_BIND}"
  rm -f "$IMGPROXY_BIND"
else
  export IMGPROXY_BIND="${IMGPROXY_BIND:-127.0.0.1:8081}"
  unset IMGPROXY_UNIX_SOCKET
fi

export IMGPROXY_LOCAL_FILESYSTEM_ROOT="${IMGPROXY_LOCAL_FILESYSTEM_ROOT:-/tmp/imgproxy}"
mkdir -p "$IMGPROXY_LOCAL_FILESYSTEM_ROOT"

export IMGPROXY_MAX_SRC_FILE_SIZE="${IMGPROXY_MAX_SRC_FILE_SIZE:-10485760}"
export IMGPROXY_MAX_SRC_RESOLUTION="${IMGPROXY_MAX_SRC_RESOLUTION:-25}"
export IMGPROXY_MAX_RESULT_DIMENSION="${IMGPROXY_MAX_RESULT_DIMENSION:-1024}"
export IMGPROXY_MAX_ANIMATION_FRAMES="${IMGPROXY_MAX_ANIMATION_FRAMES:-1}"
export IMGPROXY_SANITIZE_SVG="${IMGPROXY_SANITIZE_SVG:-true}"
export IMGPROXY_ALLOW_PRIVATE_SOURCE_ADDRESSES="${IMGPROXY_ALLOW_PRIVATE_SOURCE_ADDRESSES:-false}"
export IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES="${IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES:-false}"
export IMGPROXY_ALLOW_LINK_LOCAL_SOURCE_ADDRESSES="${IMGPROXY_ALLOW_LINK_LOCAL_SOURCE_ADDRESSES:-false}"

imgproxy &
IMGPROXY_PID=$!

bun run src/server.ts &
SERVER_PID=$!

cleanup() {
  kill "$SERVER_PID" "$IMGPROXY_PID" 2>/dev/null || true
  if [[ "$IMGPROXY_NETWORK" == unix* ]]; then
    rm -f "$IMGPROXY_BIND"
  fi
}
trap cleanup EXIT INT TERM

wait -n "$SERVER_PID" "$IMGPROXY_PID"
