name = "ens-api"
main = "src/index.ts"
compatibility_date = "2025-10-03"

[observability]
enabled = true

# The necessary secrets are:
# - ETH_RPC
# Run `echo <VALUE> | npx wrangler secret put <NAME>` for each of these
