#!/usr/bin/env bash
set -euo pipefail

export PORT="${PORT:-3000}"
export IMGPROXY_BIND="${IMGPROXY_BIND:-127.0.0.1:8081}"
export IMGPROXY_MAX_SRC_FILE_SIZE="${IMGPROXY_MAX_SRC_FILE_SIZE:-10485760}"
export IMGPROXY_MAX_SRC_RESOLUTION="${IMGPROXY_MAX_SRC_RESOLUTION:-25}"
export IMGPROXY_MAX_RESULT_DIMENSION="${IMGPROXY_MAX_RESULT_DIMENSION:-1024}"
export IMGPROXY_MAX_ANIMATION_FRAMES="${IMGPROXY_MAX_ANIMATION_FRAMES:-1}"
export IMGPROXY_SANITIZE_SVG="${IMGPROXY_SANITIZE_SVG:-true}"
export IMGPROXY_ALLOW_PRIVATE_SOURCE_ADDRESSES="${IMGPROXY_ALLOW_PRIVATE_SOURCE_ADDRESSES:-false}"
export IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES="${IMGPROXY_ALLOW_LOOPBACK_SOURCE_ADDRESSES:-false}"
export IMGPROXY_ALLOW_LINK_LOCAL_SOURCE_ADDRESSES="${IMGPROXY_ALLOW_LINK_LOCAL_SOURCE_ADDRESSES:-false}"

imgproxy &
IMGPROXY_PID=$!

bun run src/server.ts &
SERVER_PID=$!

cleanup() {
  kill "$SERVER_PID" "$IMGPROXY_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

wait -n "$SERVER_PID" "$IMGPROXY_PID"
